// Catalogue pédagogique — 4 parcours, ~40 cours
// Le contenu est techniquement correct : pas de simplifications trompeuses.

export type Level = 'debutant' | 'intermediaire' | 'avance' | 'expert';

export type Course = {
  slug: string;
  trackSlug: string;
  title: string;
  level: Level;
  durationMin: number;
  objective: string;
  simple: string;
  technical: string;
  examples: string;
  mistakes: string;
  keyTakeaways: string[];
  domains: string[]; // DomainKey[]
};

export const TRACKS = [
  {
    slug: 'fondamentaux',
    title: 'Fondamentaux du hardware',
    level: 'debutant',
    description: 'Les bases pour comprendre comment fonctionne un ordinateur et identifier chaque composant.',
  },
  {
    slug: 'intermediaire',
    title: 'Hardware intermédiaire',
    level: 'intermediaire',
    description: 'Architecture CPU, GPU, mémoire, interfaces et électronique de la carte mère.',
  },
  {
    slug: 'avance',
    title: 'Hardware avancé',
    level: 'avance',
    description: 'Micro-architecture, Infinity Fabric, VRM, PCIe, power limits et thermique.',
  },
  {
    slug: 'technicien',
    title: 'Niveau technicien',
    level: 'expert',
    description: 'Montage, BIOS, installation OS, diagnostic POST, stabilité et maintenance.',
  },
];

export const COURSES: Course[] = [
  // ============ FONDAMENTAUX ============
  {
    slug: 'comment-fonctionne-un-ordinateur',
    trackSlug: 'fondamentaux',
    title: "Comment fonctionne un ordinateur ?",
    level: 'debutant',
    durationMin: 8,
    objective: "Comprendre le schéma global : entrées → traitement → stockage → sortie.",
    simple: "Un PC reçoit des données (clavier, souris, fichiers), les transforme en calculs grâce au CPU et au GPU, puis affiche le résultat sur ton écran. La RAM garde les informations temporaires pendant que le SSD les garde durablement.",
    technical: "Cycle fetch–decode–execute : le CPU lit une instruction en RAM, la décode, puis l'exécute via ses unités ALU/FPU/Vectorielles. Le northbridge (aujourd'hui intégré au CPU) gère la mémoire et le PCIe. Les périphériques communiquent via bus PCIe, USB, SATA.",
    examples: "Quand tu appuies sur une touche dans un jeu : clavier (USB) → Southbridge/PCH → CPU (calculs physiques) → GPU (rendu 3D) → framebuffer en VRAM → HDMI/DP → écran. Chaque étape prend une fraction de milliseconde.",
    mistakes: "Croire que le SSD fait les calculs : il stocke seulement. Confondre RAM et stockage : la RAM est volatile (données perdues à l'extinction), le SSD est persistant.",
    keyTakeaways: [
      "Un PC = CPU + GPU + RAM + Stockage + Carte mère + Alimentation",
      "Les données circulent via le CPU (cerveau) et passent par la RAM (mémoire de travail)",
      "Le GPU est spécialisé dans les calculs parallèles (3D, IA, vidéo)",
    ],
    domains: ['cpu', 'gpu', 'ram', 'storage', 'motherboard'],
  },
  {
    slug: 'cpu',
    trackSlug: 'fondamentaux',
    title: 'Le CPU — Processeur central',
    level: 'debutant',
    durationMin: 10,
    objective: "Comprendre le rôle du CPU, ses cœurs, threads et sa fréquence.",
    simple: "Le CPU est le cerveau du PC. Il exécute les instructions des programmes. Plus il a de cœurs et plus sa fréquence est élevée, plus il est rapide.",
    technical: "Le CPU exécute un flux d'instructions x86 (Intel/AMD). Chaque cœur a ses propres unités ALU, FPU, et caches L1/L2. L'Hyper-Threading (Intel) / SMT (AMD) duplique les registres architecturaux pour exécuter 2 threads par cœur physique. La fréquence indique le nombre de cycles par seconde (1 cycle = 1 tick d'horloge à ~0,3 ns à 3 GHz).",
    examples: "Un Ryzen 7 7800X3D a 8 cœurs / 16 threads, 4,2 GHz de base et jusqu'à 5 GHz en boost. Un Core i5-13400 a 10 cœurs (6P+4E) / 16 threads.",
    mistakes: "Penser que GHz = performance globale (un CPU plus récent à fréquence identique est bien plus rapide grâce à l'IPC). Confondre cœurs physiques et logiques.",
    keyTakeaways: [
      "Cœur physique = unité d'exécution réelle",
      "Thread (logique) = virtualisation via SMT/HT",
      "Fréquence + IPC + nombre de cœurs = performance",
      "L'IPC a plus d'impact que la fréquence entre deux générations",
    ],
    domains: ['cpu', 'arch_cpu'],
  },
  {
    slug: 'gpu',
    trackSlug: 'fondamentaux',
    title: 'Le GPU — Processeur graphique',
    level: 'debutant',
    durationMin: 10,
    objective: "Comprendre le rôle du GPU, VRAM et pipelines.",
    simple: "Le GPU calcule les images à afficher. Il est excellent pour faire la même opération sur des milliers de données en parallèle (pixels, vertices).",
    technical: "Le GPU contient des centaines voire milliers de shaders (CUDA cores NVIDIA / Stream Processors AMD). Les architectures modernes (Ada Lovelace, RDNA 3) utilisent des unités matricielles pour加速er l'IA (DLSS, FSR) et le ray tracing (RT cores / Ray Accelerators).",
    examples: "Une RTX 4070 Super a 7168 CUDA cores, 224 Tensor cores (DLSS) et 56 RT cores. Une RX 7800 XT a 3840 Stream Processors et 60 Ray Accelerators.",
    mistakes: "Croire que plus de VRAM = GPU plus rapide (la VRAM est importante mais la puissance brute compte davantage). Confondre RAM système et VRAM.",
    keyTakeaways: [
      "GPU = parallélisme massif pour pixels, IA et calcul scientifique",
      "VRAM = mémoire dédiée au GPU (GDDR6X, GDDR7, HBM)",
      "Le GPU a aussi un rôle dans l'IA, le calcul scientifique et le rendu",
    ],
    domains: ['gpu', 'arch_gpu'],
  },
  {
    slug: 'ram',
    trackSlug: 'fondamentaux',
    title: 'La RAM — Mémoire vive',
    level: 'debutant',
    durationMin: 8,
    objective: "Comprendre la mémoire vive : DDR4, DDR5, capacité, fréquence.",
    simple: "La RAM stocke temporairement les données utilisées par tes programmes. Plus tu as de RAM, plus tu peux faire tourner de choses simultanément.",
    technical: "DDR = Double Data Rate : transfère 2 fois par cycle d'horloge. DDR5 double la bande passante de la DDR4, fonctionne à des fréquences plus élevées (4800-8000 MT/s), intègre le PMIC sur le module et gère la correction ECC sur la plupart des modèles.",
    examples: "16 Go DDR5-6000 CL30 = bon compromis gaming/productivité. 32 Go recommandé pour la création de contenu. La latence CAS (CL) mesure le délai en cycles entre une demande et la première donnée.",
    mistakes: "Penser que la fréquence seule compte : le CL et les timings sont aussi cruciaux. Mélanger DDR4 et DDR5 : incompatibles physiquement et électriquement.",
    keyTakeaways: [
      "DDR5 = standard actuel, plus rapide et économe",
      "Capacité : 16 Go minimum, 32 Go confortable",
      "Fréquence (MT/s) et latence CAS (CL) sont les deux métriques clés",
    ],
    domains: ['ram', 'memory_tech'],
  },
  {
    slug: 'stockage',
    trackSlug: 'fondamentaux',
    title: 'Le stockage — SSD, NVMe, SATA',
    level: 'debutant',
    durationMin: 8,
    objective: "Différencier SSD SATA, NVMe et HDD.",
    simple: "Le stockage garde tes fichiers quand le PC est éteint. Les SSD NVMe sont les plus rapides, les HDD les plus lents mais moins chers au Go.",
    technical: "SATA III = 6 Gbps (~550 Mo/s réels). NVMe = PCIe 3.0 x4 = 3,5 Go/s, PCIe 4.0 x4 = 7 Go/s, PCIe 5.0 x4 = 14 Go/s. Les SSD utilisent de la NAND TLC ou QLC, avec un contrôleur (Phison, Samsung, Silicon Motion) et un cache DRAM ou HMB.",
    examples: "Un Samsung 990 Pro 2 To NVMe PCIe 4.0 lit à 7 450 Mo/s. Un SSD SATA comme le Crucial MX500 culmine à 560 Mo/s.",
    mistakes: "Croire qu'un SSD NVMe PCIe 5.0 est 5x plus rapide en usage réel : la plupart des usages ne dépassent pas 3 Go/s.",
    keyTakeaways: [
      "NVMe = SSD rapide branché sur PCIe",
      "SATA = ancien standard, limité à ~550 Mo/s",
      "Le SSD est indispensable : un HDD en 2026 = mauvaise expérience",
    ],
    domains: ['storage', 'interfaces'],
  },
  {
    slug: 'carte-mere',
    trackSlug: 'fondamentaux',
    title: 'La carte mère',
    level: 'debutant',
    durationMin: 10,
    objective: "Identifier les éléments visibles d'une carte mère et son rôle central.",
    simple: "C'est la carte qui relie tous les composants entre eux. Elle définit quel CPU, RAM et connecteurs tu peux utiliser.",
    technical: "Le chipset (Z890, B650, X870) gère les ports PCIe supplémentaires, USB, SATA, réseau. Le socket (LGA1851, AM5) accueille le CPU. Les slots DIMM accueillent la RAM. Les slots M.2 (Key M) reçoivent les SSD NVMe.",
    examples: "Une carte mère ATX a 4 slots RAM, 2-4 slots M.2, plusieurs PCIe x16. Les formats : ATX, mATX, ITX.",
    mistakes: "Acheter une carte LGA1700 avec un CPU AM5 : impossible, sockets incompatibles. Oublier que le chipset peut limiter le PCIe ou l'overclocking.",
    keyTakeaways: [
      "Socket + chipset = compatibilité CPU",
      "Slots DIMM = RAM (nombre et génération)",
      "Slots M.2 + SATA = stockage",
      "PCIe x16 = GPU et cartes d'extension",
    ],
    domains: ['motherboard', 'compatibility'],
  },
  {
    slug: 'alimentation',
    trackSlug: 'fondamentaux',
    title: "L'alimentation (PSU)",
    level: 'debutant',
    durationMin: 7,
    objective: "Comprendre la puissance, les certifications 80 Plus et les connecteurs.",
    simple: "L'alimentation transforme le courant de ta prise (230V AC) en tensions utilisables par les composants (12V, 5V, 3,3V DC). Elle doit être dimensionnée correctement.",
    technical: "Une PSU de qualité a une certification 80 Plus (Bronze, Silver, Gold, Platinum, Titanium) qui mesure le rendement énergétique. Les connecteurs clés : 24-pin ATX, 8-pin EPS (CPU), 6+2-pin PCIe (GPU), SATA power, 12VHPWR (nouveau connecteur GPU PCIe 5.0).",
    examples: "Un PC gaming RTX 4070 + Ryzen 7 consomme ~450W. Une PSU 650W Gold laisse de la marge. Le 12VHPWR supporte jusqu'à 600W sur un seul câble.",
    mistakes: "Sous-dimensionner la PSU : instability, crashes. Confondre puissance crête et continue. Utiliser des câbles modulaires d'une autre marque : risque de court-circuit.",
    keyTakeaways: [
      "Certification 80 Plus = rendement et qualité",
      "12VHPWR = nouveau connecteur pour GPU récents",
      "Toujours dimensionner avec ~30% de marge",
    ],
    domains: ['psu'],
  },
  {
    slug: 'refroidissement',
    trackSlug: 'fondamentaux',
    title: 'Le refroidissement',
    level: 'debutant',
    durationMin: 8,
    objective: "Comprendre aircooling, watercooling et pâte thermique.",
    simple: "Les composants chauffent quand ils fonctionnent. Il faut évacuer cette chaleur pour qu'ils ne s'abîment pas.",
    technical: "Aircooling = dissipateur + ventilateurs. Watercooling (AIO) = pompe + waterblock + radiateur. La pâte thermique (TIM) comble les micro-imperfections entre le CPU et le dissipateur. Les bons modèles : Thermal Grizzly Kryonaut, Noctua NT-H2.",
    examples: "Un Noctua NH-D15 refroidit un Ryzen 7 7800X3D en silence. Un AIO 360mm (NZXT Kraken, Arctic Liquid Freezer III) gère les CPU plus gourmands comme le i9-14900K.",
    mistakes: "Trop de pâte thermique : elle déborde et peut causer des courts-circuits. Mauvais montage du ventirad : les performances chutent.",
    keyTakeaways: [
      "Aircooling = simple, efficace, silencieux",
      "AIO = performances supérieures, plus cher",
      "La pâte thermique doit être appliquée correctement",
    ],
    domains: ['cooling', 'thermal'],
  },
  {
    slug: 'boitier',
    trackSlug: 'fondamentaux',
    title: 'Le boîtier',
    level: 'debutant',
    durationMin: 6,
    objective: "Comprendre les formats de boîtier et l'airflow.",
    simple: "Le boîtier protège et organise les composants. Un bon airflow = air frais qui entre par l'avant/bas et sort par l'arrière/haut.",
    technical: "Les formats : ATX, mATX, ITX. Le clearance CPU cooler (hauteur max du ventirad) et GPU length (longueur max de la carte graphique) sont des contraintes critiques. Le cable management est facilité par les passages à l'arrière du plateau.",
    examples: "Un Lian Li O11 Dynamic accepte des GPU 420mm et watercooling 360mm. Un NZXT H1 Flow est un ITX compact.",
    mistakes: "Acheter un GPU trop long pour le boîtier. Oublier la hauteur du ventirad.",
    keyTakeaways: [
      "ATX = standard, mATX = compact, ITX = mini",
      "Vérifier la longueur GPU et la hauteur CPU cooler",
      "Airflow avant-arrière optimal",
    ],
    domains: ['cooling', 'build'],
  },
  {
    slug: 'peripheriques',
    trackSlug: 'fondamentaux',
    title: 'Les périphériques',
    level: 'debutant',
    durationMin: 5,
    objective: "Comprendre clavier, souris, écran, audio.",
    simple: "Ce sont les éléments d'interaction : clavier, souris, écran, casque.",
    technical: "Écran : résolution (1080p, 1440p, 4K), taux de rafraîchissement (60, 144, 240, 360 Hz), technologies (IPS, VA, OLED), HDR. Claviers : mécanique (switches Cherry MX, Kailh, Gateron) ou membrane. Souris : capteur (capteur Pixart 3395 par exemple), DPI, poids.",
    examples: "Un écran 27\" 1440p 165 Hz IPS est le sweet spot gaming. Un clavier mécanique avec switches MX Brown = bon pour taper et jouer.",
    mistakes: "Acheter un écran 4K 60 Hz pour du gaming : le GPU ne suivra pas en FPS. Un clavier membrane pour du FPS compétitif : précision moindre.",
    keyTakeaways: [
      "Écran : résolution + rafraîchissement + technologie",
      "Clavier : mécanique > membrane pour la plupart des usages",
      "Souris : capteur moderne, poids adapté à ton style",
    ],
    domains: ['pcb'],
  },

  // ============ INTERMÉDIAIRE ============
  {
    slug: 'architecture-cpu',
    trackSlug: 'intermediaire',
    title: 'Architecture CPU — pipeline, cache, IPC',
    level: 'intermediaire',
    durationMin: 12,
    objective: "Comprendre le pipeline d'instruction et l'impact de l'IPC.",
    simple: "Le CPU décompose chaque instruction en étapes pour en exécuter plusieurs simultanément. L'IPC mesure combien d'instructions il effectue par cycle.",
    technical: "Pipeline classique : Fetch → Decode → Rename → Allocate → Execute → Writeback → Retire. Les architectures modernes (Zen 5, Lion Cove) atteignent 5-6 instructions par cycle grâce à des unités superscalaires, du branch prediction (BTB, RAS) et de l'exécution spéculative.",
    examples: "Entre Zen 3 et Zen 5, AMD a gagné ~25% d'IPC. Entre Alder Lake et Raptor Lake, Intel a gagné ~15% d'IPC. Cela explique pourquoi un CPU à fréquence identique est sensiblement plus rapide.",
    mistakes: "Croire que la fréquence est le seul indicateur. Ignorer le rôle du cache mémoire.",
    keyTakeaways: [
      "IPC = instructions par cycle (facteur de performance majeur)",
      "Pipeline = parallélisme au sein d'une instruction",
      "Cache = mémoire ultra-rapide sur le CPU",
    ],
    domains: ['cpu', 'arch_cpu'],
  },
  {
    slug: 'architectures-gpu',
    trackSlug: 'intermediaire',
    title: 'Architectures GPU — SM, ROP, TMU',
    level: 'intermediaire',
    durationMin: 12,
    objective: "Comprendre les unités d'un GPU moderne.",
    simple: "Un GPU est composé de nombreux Streaming Multiprocessors (SM chez NVIDIA) ou Compute Units (CU chez AMD) qui exécutent les shaders en parallèle.",
    technical: "SM/CU contient : unités SIMD (32 threads NVIDIA = warp, 64 threads AMD = wavefront), unités Tensor, unités RT, scheduler dual-issue. ROP = Render Output Unit (écriture pixels finale), TMU = Texture Mapping Unit (filtrage textures).",
    examples: "AD102 (RTX 4090) : 128 SM, 18 176 CUDA cores. Navi 32 (RX 7800 XT) : 60 CU, 3 840 Stream Processors.",
    mistakes: "Comparer CUDA cores et Stream Processors 1:1 (les architectures diffèrent). Ignorer la bande passante mémoire.",
    keyTakeaways: [
      "GPU = grilles de SM/CU",
      "ROP et TMU gèrent la sortie d'image",
      "RT cores / Ray Accelerators = ray tracing",
      "Tensor cores = IA et upscaling",
    ],
    domains: ['gpu', 'arch_gpu'],
  },
  {
    slug: 'vram',
    trackSlug: 'intermediaire',
    title: 'La VRAM',
    level: 'intermediaire',
    durationMin: 8,
    objective: "Comprendre GDDR6X, GDDR7, HBM et l'impact sur les performances.",
    simple: "La VRAM est la mémoire dédiée au GPU. Plus elle est rapide et plus sa capacité est grande, mieux le GPU performe en haute résolution.",
    technical: "GDDR6X (NVIDIA RTX 40/50) atteint 21-32 Gbps par pin avec PAM3. GDDR7 (standard 2025+) atteint 32-48 Gbps avec PAM3. HBM3 (data center) atteint 819 Go/s par stack via interposer silicium. La bande passante = fréquence × bus width.",
    examples: "Une RTX 4090 a 24 Go GDDR6X sur bus 384 bits = 1 008 Go/s. Une RX 7900 XTX a 24 Go GDDR6 sur 384 bits = 960 Go/s.",
    mistakes: "Croire que la VRAM n'a pas d'importance en 1080p : certains jeux modernes consomment 8-12 Go en textures seules.",
    keyTakeaways: [
      "GDDR7 = standard actuel",
      "Bande passante = bus width × fréquence",
      "Capacité VRAM critique en 4K et création de contenu",
    ],
    domains: ['gpu', 'memory_tech'],
  },
  {
    slug: 'cache',
    trackSlug: 'intermediaire',
    title: 'Le cache CPU — L1, L2, L3',
    level: 'intermediaire',
    durationMin: 9,
    objective: "Comprendre la hiérarchie mémoire et son impact sur les performances.",
    simple: "Le cache est une mémoire ultra-rapide située sur le CPU. Plus le cache est gros et proche du cœur, plus le CPU est rapide.",
    technical: "L1 : 32-64 Ko par cœur, ~1 ns, séparé instructions/données. L2 : 512 Ko à 1 Mo par cœur, ~3-5 ns. L3 : 16-128 Mo partagé entre tous les cœurs, ~10-15 ns. Le cache miss vers la RAM coûte ~80-100 ns.",
    examples: "Le Ryzen 7 7800X3D a 96 Mo de L3 (3D V-Cache) ce qui le rend imbattable en gaming. Le Core i9-14900K a 36 Mo de L3.",
    mistakes: "Ignorer le rôle du cache dans la performance gaming (les CPUs X3D AMD dominent le gaming grâce au L3 géant).",
    keyTakeaways: [
      "L1/L2 : rapides, privées par cœur",
      "L3 : partagé, plus gros mais plus lent",
      "Plus de L3 = meilleure performance dans les jeux (cache locality)",
    ],
    domains: ['cpu', 'memory_tech'],
  },
  {
    slug: 'frequences-cpu',
    trackSlug: 'intermediaire',
    title: 'Fréquences — Base, Boost, PBO',
    level: 'intermediaire',
    durationMin: 8,
    objective: "Comprendre les mécanismes de variation de fréquence.",
    simple: "La fréquence du CPU varie selon la charge et la température. En boost, elle dépasse la fréquence de base si les conditions le permettent.",
    technical: "La base = fréquence minimale garantie. Le boost = fréquence max selon charge, thermique, et limites de puissance. PBO (AMD) et TVB/PL (Intel) ajustent dynamiquement. La fréquence réelle dépend de l'IPC, du nombre de cœurs actifs, et des limites PL1/PL2.",
    examples: "Un Ryzen 9 7950X a une base de 4,5 GHz et un boost de 5,7 GHz sur 1 cœur, 5,2 GHz en all-core.",
    mistakes: "Penser que la fréquence affichée est fixe. Elle varie selon l'usage.",
    keyTakeaways: [
      "Base = minimum garanti",
      "Boost = max selon charge et thermique",
      "PBO / TVB = mécanismes d'extension du boost",
    ],
    domains: ['cpu', 'arch_cpu'],
  },
  {
    slug: 'coeurs-threads',
    trackSlug: 'intermediaire',
    title: "Cœurs et threads — SMT, Hyper-Threading",
    level: 'intermediaire',
    durationMin: 7,
    objective: "Comprendre l'impact du multi-threading.",
    simple: "Le SMT permet à un cœur physique d'exécuter deux threads en parallèle. C'est utile pour les tâches lourdes mais parfois néfaste pour le gaming.",
    technical: "SMT (Simultaneous Multithreading) duplique les registres architecturaux et le frontend mais partage les unités d'exécution. Gain typique : 15-25% sur charges multi-thread, parfois négatif si mal optimisé.",
    examples: "Un Ryzen 9 7950X : 16 cœurs / 32 threads. Désactiver le SMT peut améliorer les FPS dans certains jeux très anciens ou mal optimisés (ex: certains FPS compétitifs).",
    mistakes: "Penser que 32 threads = 32x plus rapide qu'1 thread (la plupart des apps ne sont pas multi-threadées).",
    keyTakeaways: [
      "SMT = ~20% de gain moyen",
      "Peut être désactivé pour gagner en single-thread",
      "Crucial pour rendu, compilation, streaming",
    ],
    domains: ['cpu', 'arch_cpu'],
  },
  {
    slug: 'ddr4-vs-ddr5',
    trackSlug: 'intermediaire',
    title: 'DDR4 vs DDR5 — timings, XMP, EXPO',
    level: 'intermediaire',
    durationMin: 10,
    objective: "Comprendre les timings mémoire et les profils d'overclocking.",
    simple: "La DDR5 est plus rapide et plus efficace que la DDR4. Les profils XMP/EXPO permettent d'overclocker ta RAM en un clic.",
    technical: "Timings principaux : CL (CAS Latency), tRCD, tRP, tRAS. La latence réelle en ns = CL × 2000 / fréquence MT/s. DDR4-3200 CL16 = 10 ns, DDR5-6000 CL30 = 10 ns (similaire malgré CL plus élevé). XMP = Intel eXtreme Memory Profile, EXPO = AMD Extended Profile for Overclocking.",
    examples: "G.Skill Trident Z5 RGB 32 Go DDR5-6000 CL30 est le sweet spot AMD AM5. Kingston Fury Beast 32 Go DDR5-7200 CL34 pour Intel LGA1700.",
    mistakes: "Activer XMP mais la carte mère ne supporte pas la fréquence : boot fail ou downclock automatique.",
    keyTakeaways: [
      "DDR5 > DDR4 en bande passante",
      "Latence réelle = CL / fréquence",
      "XMP/EXPO = activer pour overclocking RAM",
    ],
    domains: ['ram', 'memory_tech', 'overclock'],
  },
  {
    slug: 'pcie',
    trackSlug: 'intermediaire',
    title: 'PCIe — Générations, lanes, connecteurs',
    level: 'intermediaire',
    durationMin: 9,
    objective: "Comprendre PCIe x1, x4, x16 et leur impact.",
    simple: "PCIe est le bus qui connecte GPU, SSD NVMe et cartes d'extension. Plus il y a de lignes (lanes) et plus la version est récente, plus c'est rapide.",
    technical: "PCIe est une connexion série point-à-point. PCIe 3.0 = 985 Mo/s par lane. PCIe 4.0 = 1,97 Go/s. PCIe 5.0 = 3,94 Go/s. Un GPU PCIe 4.0 x16 = 31,5 Go/s. Le chipset ajoute des lanes mais souvent en PCIe 4.0 partageant la bande passante avec le CPU.",
    examples: "Un GPU occupe 16 lanes. Un SSD NVMe PCIe 4.0 occupe 4 lanes. Le CPU Ryzen 7000 a 28 lanes PCIe dont 24 utilisables.",
    mistakes: "Croire qu'un GPU PCIe 3.0 x16 est identique à un PCIe 5.0 x16 : la différence est minime en jeu mais peut exister dans certains calculs GPU.",
    keyTakeaways: [
      "PCIe 5.0 = standard actuel GPU/CPU",
      "Lanes : 16 pour GPU, 4 pour NVMe",
      "Chipset partage la bande passante avec CPU",
    ],
    domains: ['interfaces', 'motherboard'],
  },
  {
    slug: 'nvme-vs-sata',
    trackSlug: 'intermediaire',
    title: 'NVMe vs SATA — performances et protocoles',
    level: 'intermediaire',
    durationMin: 7,
    objective: "Comprendre pourquoi NVMe est plus rapide que SATA.",
    simple: "NVMe utilise le PCIe directement, sans passer par le contrôleur SATA. Cela élimine le goulot d'étranglement.",
    technical: "SATA utilise AHCI (Advanced Host Controller Interface), conçu à l'époque des HDD. NVMe (Non-Volatile Memory Express) est optimisé pour les SSD : file d'attente de 64K commandes vs 32 pour AHCI, latence réduite de 5-10 µs.",
    examples: "Un Samsung 870 EVO SATA atteint 560 Mo/s. Un Samsung 990 Pro NVMe PCIe 4.0 atteint 7 450 Mo/s, soit 13x plus rapide.",
    mistakes: "Penser que NVMe est 13x plus rapide en usage réel : le boot et les transferts massifs sont améliorés, mais l'ouverture d'apps est déjà très rapide en SATA.",
    keyTakeaways: [
      "NVMe = PCIe direct, optimisé",
      "SATA = ancien protocole, bridé à ~550 Mo/s",
      "M.2 Key M = NVMe, M.2 Key B = SATA",
    ],
    domains: ['storage', 'interfaces'],
  },
  {
    slug: 'vrm-intro',
    trackSlug: 'intermediaire',
    title: 'VRM — Introduction à l\'alimentation du CPU',
    level: 'intermediaire',
    durationMin: 10,
    objective: "Comprendre le rôle du VRM et son impact.",
    simple: "Le VRM convertit le 12V de l'alimentation en une tension précise pour le CPU. S'il est faible, le CPU ne sera pas stable à pleine charge.",
    technical: "Le VRM est composé de phases : chacune contient un MOSFET haut, un MOSFET bas, un driver, et une inductance. Le PWM controller synchronise les phases. Plus il y a de phases et plus elles sont robustes, mieux le CPU est alimenté.",
    examples: "Une carte mère B650 avec 8+2 phases peut gérer un Ryzen 9 7950X. Une B650 avec 6+1 phases = OC limité sur CPU haut de gamme.",
    mistakes: "Penser que 'plus de phases = toujours mieux' : la qualité des composants (MOSFET, inductances) compte autant.",
    keyTakeaways: [
      "VRM = alimentation du CPU",
      "Phases = qualité d'alimentation",
      "Critique pour l'overclocking et CPU haut de gamme",
    ],
    domains: ['vrm', 'motherboard'],
  },
  {
    slug: 'chipsets',
    trackSlug: 'intermediaire',
    title: 'Chipsets — Z890, B650, X870',
    level: 'intermediaire',
    durationMin: 8,
    objective: "Différencier les chipsets et leurs fonctionnalités.",
    simple: "Le chipset détermine les fonctionnalités et le prix de la carte mère. Z/X = haut de gamme, B = milieu, H = entrée de gamme.",
    technical: "AMD AM5 : X870E (Extreme, 28 lanes PCIe 5.0 CPU + 12 chipset), X870 (24 + 8), B650 (24 + 8), B840 (entry). Intel LGA1851 : Z890 (haut de gamme, OC), B860 (milieu), H810 (entrée).",
    examples: "Une MSI MAG B650 Tomahawk WiFi = excellent rapport qualité/prix pour Ryzen 7000. Une ASUS ROG Maximus Z890 Hero = overclocking extrême Intel.",
    mistakes: "Acheter une H610 pour un Core i9 : chipset trop faible, pas d'OC,供电 insuffisant.",
    keyTakeaways: [
      "Chipset = fonctionnalités + prix",
      "Série Z/X = OC + plus de ports",
      "Série B/H = suffisant pour usage standard",
    ],
    domains: ['motherboard', 'compatibility'],
  },
  {
    slug: 'bios-uefi',
    trackSlug: 'intermediaire',
    title: 'BIOS / UEFI',
    level: 'intermediaire',
    durationMin: 8,
    objective: "Comprendre le rôle du firmware UEFI.",
    simple: "Le BIOS/UEFI est le logiciel qui démarre ta carte mère avant Windows. C'est là que tu règles la RAM, l'ordre de boot, et l'overclocking.",
    technical: "UEFI a remplacé le BIOS Legacy en 2010+. Il supporte le Secure Boot, le partitionnement GPT, et des interfaces graphiques. Les fabricants : AMI (American Megatrends), Phoenix, Insyde.",
    examples: "Pour activer XMP/EXPO, il faut entrer dans le BIOS (DEL ou F2 au démarrage). Pour flasher le BIOS, on télécharge le fichier sur le site du fabricant de la carte mère.",
    mistakes: "Ne pas mettre à jour le BIOS avant d'installer un nouveau CPU : incompatibilité possible.",
    keyTakeaways: [
      "UEFI = firmware moderne de la carte mère",
      "Lieu d'activation XMP/EXPO et OC",
      "Mise à jour pour supporter de nouveaux CPU",
    ],
    domains: ['firmware', 'motherboard'],
  },

  // ============ AVANCÉ ============
  {
    slug: 'zen-architecture',
    trackSlug: 'avance',
    title: 'Architecture AMD Zen 5',
    level: 'avance',
    durationMin: 12,
    objective: "Approfondir Zen 5 : pipeline, branch prediction, unités.",
    simple: "Zen 5 est l'architecture AMD la plus récente (2024+). Elle apporte un gain d'IPC de ~16% par rapport à Zen 4.",
    technical: "Zen 5 : frontend wide (6-wide decode vs 4-wide Zen 4), exécution 8 ALU par cycle, 3 unités 512-bit (AVX-512 amélioré), cache L2 1 Mo par cœur, branch prediction avec TAGE, op cache étendu.",
    examples: "Ryzen 9 9950X : 16 cœurs / 32 threads, Zen 5, 4,3 GHz base / 5,7 GHz boost, 80 Mo L3, AM5.",
    mistakes: "Croire que Zen 5 et Zen 4 ont les mêmes performances single-thread : non, ~16% d'écart en faveur de Zen 5.",
    keyTakeaways: [
      "Zen 5 = +16% d'IPC vs Zen 4",
      "Frontend 6-wide",
      "Excellent en single-thread et multi-thread",
    ],
    domains: ['cpu', 'arch_cpu'],
  },
  {
    slug: 'infinity-fabric',
    trackSlug: 'avance',
    title: 'Infinity Fabric — interconnect AMD',
    level: 'avance',
    durationMin: 8,
    objective: "Comprendre le rôle de l'Infinity Fabric.",
    simple: "L'Infinity Fabric relie les cœurs entre eux et au contrôleur mémoire. Sa fréquence doit être synchronisée avec la RAM.",
    technical: "Infinity Fabric (IF) est un interconnect à haute vitesse qui relie les CCX (Core Complex = 8 cœurs) entre eux et au contrôleur mémoire. Sur AM5, la fréquence IF est dérivée de la fréquence MCLK (RAM). Le ratio idéal est 1:1 jusqu'à 2000 MHz, puis 2:1 au-delà.",
    examples: "Ryzen 7 7800X3D : un seul CCX, latence minimale. Ryzen 9 7950X : deux CCX, communication IF entre CCX. DDR5-6000 = ratio 1:1 idéal.",
    mistakes: "Penser que plus de RAM = plus d'IF : la fréquence de l'IF dépend directement de la fréquence RAM.",
    keyTakeaways: [
      "IF = bus interne AMD",
      "Ratio MCLK:FCLK optimal = 1:1",
      "DDR5-6000 = sweet spot AM5",
    ],
    domains: ['cpu', 'arch_cpu', 'memory_tech'],
  },
  {
    slug: 'pcie-lanes-bifurcation',
    trackSlug: 'avance',
    title: 'PCIe lanes et bifurcation',
    level: 'avance',
    durationMin: 8,
    objective: "Comprendre l'allocation des lanes PCIe.",
    simple: "Le CPU fournit un nombre limité de lanes. Le reste vient du chipset. La bifurcation permet de diviser x16 en x8/x8 ou x4/x4/x4/x4.",
    technical: "Bifurcation = diviser un slot PCIe x16 en plusieurs slots plus petits. Utilisé pour installer plusieurs SSD NVMe sur une seule ligne CPU. Le chipset peut aussi partager ses lanes via un switch PCIe (comme les ASM1480 d'ASMedia).",
    examples: "Carte mère ASRock Rack : bifurcation x16 → 4x NVMe x4 pour setup serveur.",
    mistakes: "Croire que la bifurcation est gratuite : elle divise la bande passante, utile surtout en serveur.",
    keyTakeaways: [
      "Bifurcation = diviser les lanes PCIe",
      "Utile pour serveurs et stations de travail",
      "Consomme la bande passante CPU",
    ],
    domains: ['interfaces', 'motherboard'],
  },
  {
    slug: 'vrm-phases',
    trackSlug: 'avance',
    title: 'VRM — Phases, MOSFET, LLC',
    level: 'avance',
    durationMin: 12,
    objective: "Maîtriser en profondeur le fonctionnement du VRM.",
    simple: "Le VRM est un circuit d'alimentation à découpage. Chaque phase commute rapidement pour fournir une tension stable.",
    technical: "Phase = MOSFET haut (high-side) + MOSFET bas (low-side) + driver + inductance + condensateur. Le PWM controller synchronise les phases. LLC (Load Line Calibration) ajuste la tension en fonction du courant pour éviter les chutes.",
    examples: "Carte mère haut de gamme : 20+2 phases, MOSFET 90A par phase, LLC efficace. Carte entrée de gamme : 6+1+1 phases, MOSFET 50A.",
    mistakes: "Penser que LLC = toujours activer à max : trop élevé = surtension, trop bas = chute et instabilité.",
    keyTakeaways: [
      "Phase = 1 unité de conversion",
      "Plus de phases = meilleure répartition",
      "LLC = calibrage de la chute de tension",
    ],
    domains: ['vrm', 'motherboard'],
  },
  {
    slug: 'power-limits',
    trackSlug: 'avance',
    title: 'Power Limits — PL1, PL2, PPT',
    level: 'avance',
    durationMin: 9,
    objective: "Comprendre les limites de puissance CPU.",
    simple: "Les power limits définissent la puissance maximale autorisée pour le CPU. PL1 = longue durée, PL2 = boost court.",
    technical: "PPT (AMD Package Power Tracking) = puissance totale socket. PL1 (Intel) = puissance soutenue. PL2 = puissance autorisée en boost (souvent 25% au-dessus de PL1). Tau = durée du boost PL2. EDC/TDC (Electrical/Thermal Design Current) = limites de courant.",
    examples: "Core i9-14900K : PL1=125W, PL2=253W. Ryzen 9 7950X : PPT=170W par défaut, configurable jusqu'à 230W.",
    mistakes: "Lever les power limits sans refroidissement adapté : thermal throttling immédiat.",
    keyTakeaways: [
      "PL1 = sustained power",
      "PL2 = boost power",
      "PPT = équivalent AMD",
    ],
    domains: ['cpu', 'overclock'],
  },
  {
    slug: 'overclocking',
    trackSlug: 'avance',
    title: 'Overclocking — CPU et RAM',
    level: 'avance',
    durationMin: 14,
    objective: "Apprendre à overclocker CPU et RAM en sécurité.",
    simple: "Overclocker = augmenter la fréquence au-delà des spécifications. Cela demande du refroidissement et du silicium favorable (silicon lottery).",
    technical: "Méthode : augmenter le multiplicateur par pas de 25 MHz, tester la stabilité avec Cinebench R24 (15 min) + OCCT (1h). Pour la RAM, activer XMP/EXPO puis tuner les timings manuellement. Undervolt = baisser la tension pour gagner en thermique.",
    examples: "Un Ryzen 7 7700X peut atteindre 5,4 GHz all-core stable sur les bons exemplaires. Une DDR5-6000 CL30 peut être réduite à CL28 sur certains kits Samsung B-die.",
    mistakes: "Augmenter la tension trop vite : dégradation du silicium. Oublier le LLC.",
    keyTakeaways: [
      "Overclocking = trouver le meilleur ratio perf/voltage",
      "Test de stabilité indispensable",
      "Undervolt = gagner en efficacité",
    ],
    domains: ['overclock', 'cpu', 'ram'],
  },
  {
    slug: 'thermal-throttling',
    trackSlug: 'avance',
    title: 'Thermal throttling et散热',
    level: 'avance',
    durationMin: 8,
    objective: "Comprendre quand le CPU/GPU réduit ses performances pour se protéger.",
    simple: "Quand la température dépasse la limite (95-105°C CPU, 90-110°C GPU), le composant réduit sa fréquence pour survivre. C'est le thermal throttling.",
    technical: "TJmax = température de jonction maximale. Au-delà, le CPU baisse fréquence et tension. Tj 100°C pour Ryzen 7000/9000, 100°C pour Core i9-14th, 110°C pour certaines générations Intel. La pâte thermique et le contact du ventirad sont les premières causes.",
    examples: "Un Ryzen 9 7950X mal refroidi (ventirad stock) throttle à 95°C en charge. Avec un AIO 360mm, il reste à 80-85°C.",
    mistakes: "Penser que throttling = dégât : c'est une protection. Mais en throttling permanent, les performances sont réduites.",
    keyTakeaways: [
      "Throttling = protection automatique",
      "Améliorer le refroidissement = plus de perf",
      "Pâte thermique à renouveler tous les 3-5 ans",
    ],
    domains: ['thermal', 'cooling'],
  },
  {
    slug: 'bottleneck',
    trackSlug: 'avance',
    title: 'Bottleneck — CPU vs GPU',
    level: 'avance',
    durationMin: 8,
    objective: "Comprendre quand le CPU limite le GPU et inversement.",
    simple: "Un bottleneck arrive quand un composant limite les performances des autres. Ex : GPU puissant + CPU faible = le CPU ne fournit pas assez de frames.",
    technical: "Pour identifier un bottleneck : surveiller CPU usage (tous cœurs à 100%) et GPU usage (toujours 100%). Si GPU usage < 95%, le CPU est probablement le goulet. Résolutions plus élevées = plus de charge GPU = moins de CPU bottleneck.",
    examples: "Ryzen 5 5500 + RTX 4090 : bottleneck CPU massif en 1080p. Le même combo en 4K : bottleneck réduit car le GPU travaille plus.",
    mistakes: "Penser que le bottleneck est absolu : il dépend de la résolution, du jeu, et des paramètres.",
    keyTakeaways: [
      "Bottleneck dépend de la résolution et du jeu",
      "4K = plus GPU limité, 1080p = plus CPU limité",
      "Équilibre = éviter les extrêmes",
    ],
    domains: ['diagnostic', 'build', 'benchmarks'],
  },
  {
    slug: 'frametime',
    trackSlug: 'avance',
    title: 'Frametime et 1% lows',
    level: 'avance',
    durationMin: 7,
    objective: "Comprendre les métriques réelles de fluidité.",
    simple: "Le FPS moyen ne dit pas tout. Les 1% lows et frametime montrent la régularité de l'animation.",
    technical: "Frametime = temps entre deux images en ms. 1% low = pire 1% des frametimes. Une moyenne de 60 FPS mais 1% low à 30 FPS = stuttering. Les outils : CapFrameX, PresentMon, FrameView.",
    examples: "Jeu à 60 FPS moyen, 1% low à 20 ms (50 FPS) = fluide. 60 FPS moyen, 1% low à 50 ms (20 FPS) = micro-stutters visibles.",
    mistakes: "Seulement regarder le FPS moyen : les 1% lows révèlent la fluidité réelle.",
    keyTakeaways: [
      "Frametime = ms entre images",
      "1% low = pire 1%",
      "Outil : CapFrameX / PresentMon",
    ],
    domains: ['benchmarks', 'gpu'],
  },

  // ============ TECHNICIEN ============
  {
    slug: 'montage-complet',
    trackSlug: 'technicien',
    title: 'Montage complet d\'un PC',
    level: 'expert',
    durationMin: 18,
    objective: "Maîtriser le montage étape par étape.",
    simple: "Le montage se fait hors du boîtier d'abord (CPU+RAM sur CM), puis installation dans le boîtier avec GPU, stockage et PSU.",
    technical: "Étapes : 1) Installer CPU dans socket (lever le levier, aligner triangle, pas de force). 2) RAM dans slots A2/B2 pour dual channel. 3) SSD M.2. 4) Montage CM dans boîtier avec standoff. 5) PSU dans son compartiment. 6) Câbles 24-pin et 8-pin CPU. 7) GPU dans slot PCIe x16 top. 8) Câblage panneau avant.",
    examples: "Carte mère ASUS B650, Ryzen 7 7700, 32 Go DDR5, RTX 4070, NVMe 2 To, PSU 750W Gold.",
    mistakes: "Forcer le CPU dans le socket : pins tordus (AM5) ou socket endommagé (LGA). Oublier de retirer le plastique de protection du ventirad.",
    keyTakeaways: [
      "CPU hors boîtier en premier",
      "RAM : slots A2/B2",
      "Pas de force, aligner les triangles",
      "Câblage propre = airflow meilleur",
    ],
    domains: ['build', 'diagnostic'],
  },
  {
    slug: 'installation-windows',
    trackSlug: 'technicien',
    title: 'Installation Windows et pilotes',
    level: 'expert',
    durationMin: 14,
    objective: "Maîtriser l'installation propre de Windows.",
    simple: "Créer une clé USB bootable avec Rufus, boot dessus, suivre l'assistant, puis installer les pilotes.",
    technical: "Outils : Media Creation Tool (Microsoft), Rufus (Linux). Étapes : boot sur USB (modifier ordre boot BIOS), supprimer partitions, sélectionner le bon disque, installer. Après : pilotes chipset (AMD/Intel), GPU (NVIDIA/AMD), réseau, audio.",
    examples: "Installation propre = aucun reliquat, performances optimales, moins de bugs.",
    mistakes: "Installer Windows sur un HDD mécanique : expérience désastreuse. Oublier le pilote chipset = performances réduites.",
    keyTakeaways: [
      "Clé USB ≥ 8 Go",
      "Boot order dans BIOS",
      "Pilotes chipset d'abord",
      "Activer XMP/EXPO après installation",
    ],
    domains: ['driver_os', 'build'],
  },
  {
    slug: 'post-codes-erreur',
    trackSlug: 'technicien',
    title: 'POST et codes erreur',
    level: 'expert',
    durationMin: 12,
    objective: "Diagnostiquer un PC qui ne boot pas.",
    simple: "Le POST (Power-On Self-Test) vérifie le matériel avant de booter. S'il échoue, il émet un code (bips, LED, afficheur).",
    technical: "Codes AMI BIOS : 1 bip court = OK, 1 long + 3 courts = RAM, 5 courts = CPU, 6 = chipset. Cartes mères modernes : LED debug (CPU, DRAM, VGA, BOOT) ou afficheur 2 chiffres. Les étapes : 1) Vérifier alimentation, 2) RAM, 3) GPU, 4) CPU.",
    examples: "PC ne démarre pas, LED bloquée sur DRAM = tester la RAM un stick à la fois. LED VGA = problème GPU ou PCIe.",
    mistakes: "Croire que les bips sont universels : ils dépendent du BIOS (AMI, Phoenix, UEFI).",
    keyTakeaways: [
      "LED debug = outil moderne",
      "Tester RAM et GPU un par un",
      "Clear CMOS en cas de problème",
    ],
    domains: ['diagnostic', 'firmware'],
  },
  {
    slug: 'problemes-ram',
    trackSlug: 'technicien',
    title: 'Diagnostic problèmes RAM',
    level: 'expert',
    durationMin: 10,
    objective: "Identifier et résoudre les instabilités RAM.",
    simple: "Symptômes : BSOD, freezes, redémarrages, écran noir. Tests : MemTest86 (1h minimum) + Windows Memory Diagnostic.",
    technical: "Causes : timings trop agressifs, XMP non stable, slots sales, RAM défectueuse, CMOS à reset. Méthode : tester 1 stick à la fois dans slot A2, désactiver XMP, augmenter DRAM voltage (+0.05V), relâcher timings.",
    examples: "XMP DDR5-7200 unstable ? Tester DDR5-6000 CL30 par défaut ou ajuster FCLK à 2000 MHz sur AMD.",
    mistakes: "Penser que c'est la carte mère : souvent c'est le couple CPU/RAM ou l'IMC (Integrated Memory Controller).",
    keyTakeaways: [
      "MemTest86 = référence",
      "1 stick à la fois",
      "Clear CMOS avant test",
    ],
    domains: ['diagnostic', 'ram'],
  },
  {
    slug: 'problemes-gpu',
    trackSlug: 'technicien',
    title: 'Diagnostic problèmes GPU',
    level: 'expert',
    durationMin: 10,
    objective: "Identifier les artefacts, crash et surchauffe GPU.",
    simple: "Symptômes : artefacts visuels (pixels colorés), écran noir en jeu, pilote qui crash. Tests : DDU (Display Driver Uninstaller) + réinstall propre, baisser overclock, tester autre câble/écran.",
    technical: "Artefacts = VRAM défectueuse ou sous-tension. Crash = driver ou GPU instability. Surchauffe = pâte thermique séchée ou ventilateurs HS. Outils : GPU-Z (monitoring), MSI Kombustor (stress), FurMark (stress legacy).",
    examples: "RTX 4070 artefacts en jeu : DDU en safe mode, vérifier pâte thermique GPU (si plus de 5 ans), tester autre slot PCIe.",
    mistakes: "Reinstaller le pilote sans DDU : reliquats Windows causent instabilité.",
    keyTakeaways: [
      "DDU = reset propre du pilote",
      "Artefact = souvent VRAM",
      "Pâte thermique GPU à renouveler",
    ],
    domains: ['diagnostic', 'gpu'],
  },
  {
    slug: 'problemes-stockage',
    trackSlug: 'technicien',
    title: 'Diagnostic problèmes stockage',
    level: 'expert',
    durationMin: 8,
    objective: "SSD non détecté, lenteur, erreurs SMART.",
    simple: "Symptômes : SSD absent dans BIOS, lenteur inexpliquée, crash. Vérifier : câble SATA, slot M.2, BIOS qui détecte, santé SMART via CrystalDiskInfo.",
    technical: "Causes : slot M.2 partagé avec SATA (lire le manuel), PCIe gen non négocié, pilote AHCI/NVMe manquant, firmware obsolète. Outil SMART : CrystalDiskInfo (se lit en heures, TBW, temperature).",
    examples: "SSD NVMe non détecté : changer de slot M.2, vérifier que le PCIe est activé dans BIOS, mise à jour firmware.",
    mistakes: "Ignorer les avertissements SMART : un SSD avec wear leveling > 90% approche de la fin de vie.",
    keyTakeaways: [
      "CrystalDiskInfo = monitoring SMART",
      "Vérifier slot M.2 dans manuel",
      "TBW = endurance SSD",
    ],
    domains: ['diagnostic', 'storage'],
  },
  {
    slug: 'maintenance-preventive',
    trackSlug: 'technicien',
    title: 'Maintenance préventive',
    level: 'expert',
    durationMin: 7,
    objective: "Entretenir un PC pour longévité et performances.",
    simple: "Tous les 6-12 mois : nettoyage poussière (air sec), renouvellement pâte thermique (3-5 ans), vérification câbles, mise à jour BIOS/drivers.",
    technical: "Outils : bombe d'air sec, brosse antistatique, isopropanol 99% pour nettoyer contacts, Thermal Grizzly Kryonaut pour pâte. Logiciels : CPU-Z, GPU-Z, HWiNFO64 pour monitoring.",
    examples: "PC bruyant après 2 ans = poussière dans les ventilateurs. PC qui throttle = pâte thermique sèche.",
    mistakes: "Utiliser un aspirateur : électricité statique peut endommager les composants. Souffler trop fort avec la bombe : condensation possible.",
    keyTakeaways: [
      "Dépoussiérage tous les 6-12 mois",
      "Pâte thermique : 3-5 ans",
      "Mise à jour pilotes régulière",
    ],
    domains: ['diagnostic', 'cooling'],
  },
  {
    slug: 'benchmarks-fiables',
    trackSlug: 'technicien',
    title: 'Benchmarks fiables et interprétables',
    level: 'expert',
    durationMin: 10,
    objective: "Choisir et interpréter les benchmarks.",
    simple: "CPU : Cinebench R24 (multi et single). GPU : 3DMark Steel Nomad (modern, multi-API). Jeux : benchmarks intégrés avec frametime.",
    technical: "Outils recommandés : Cinebench R24, 3DMark Steel Nomad / Speed Way, PCMark 10, CapFrameX pour jeux. Toujours noter le hardware exact (CPU, GPU, RAM, drivers, OS). Comparer les résultats sur des bases de données comme 3DMark.",
    examples: "Un Ryzen 9 9950X atteint ~24 000 points Cinebench R24 multi. Une RTX 4090 atteint ~14 000 points 3DMark Speed Way.",
    mistakes: "Comparer des scores sur des versions différentes de benchmarks (Cinebench R23 vs R24).",
    keyTakeaways: [
      "Cinebench R24 = CPU moderne",
      "3DMark Steel Nomad = GPU moderne",
      "Noter le hardware complet",
    ],
    domains: ['benchmarks'],
  },
];
